set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[0]/C}]  -to [get_ports {fDAC0_out[0]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[10]/C}]  -to [get_ports {fDAC0_out[10]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[11]/C}]  -to [get_ports {fDAC0_out[11]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[12]/C}]  -to [get_ports {fDAC0_out[12]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[13]/C}]  -to [get_ports {fDAC0_out[13]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[14]/C}]  -to [get_ports {fDAC0_out[14]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[15]/C}]  -to [get_ports {fDAC0_out[15]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[1]/C}]  -to [get_ports {fDAC0_out[1]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[2]/C}]  -to [get_ports {fDAC0_out[2]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[3]/C}]  -to [get_ports {fDAC0_out[3]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[4]/C}]  -to [get_ports {fDAC0_out[4]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[5]/C}]  -to [get_ports {fDAC0_out[5]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[6]/C}]  -to [get_ports {fDAC0_out[6]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[7]/C}]  -to [get_ports {fDAC0_out[7]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[8]/C}]  -to [get_ports {fDAC0_out[8]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/s_out_reg[9]/C}]  -to [get_ports {fDAC0_out[9]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_0/sel_reg/C}]  -to [get_ports {fDAC0_sel}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[0]/C}]  -to [get_ports {fDAC1_out[0]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[10]/C}]  -to [get_ports {fDAC1_out[10]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[11]/C}]  -to [get_ports {fDAC1_out[11]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[12]/C}]  -to [get_ports {fDAC1_out[12]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[13]/C}]  -to [get_ports {fDAC1_out[13]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[14]/C}]  -to [get_ports {fDAC1_out[14]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[15]/C}]  -to [get_ports {fDAC1_out[15]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[1]/C}]  -to [get_ports {fDAC1_out[1]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[2]/C}]  -to [get_ports {fDAC1_out[2]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[3]/C}]  -to [get_ports {fDAC1_out[3]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[4]/C}]  -to [get_ports {fDAC1_out[4]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[5]/C}]  -to [get_ports {fDAC1_out[5]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[6]/C}]  -to [get_ports {fDAC1_out[6]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[7]/C}]  -to [get_ports {fDAC1_out[7]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[8]/C}]  -to [get_ports {fDAC1_out[8]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/s_out_reg[9]/C}]  -to [get_ports {fDAC1_out[9]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_1/sel_reg/C}]  -to [get_ports {fDAC1_sel}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[0]/C}]  -to [get_ports {fDAC2_out[0]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[10]/C}]  -to [get_ports {fDAC2_out[10]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[11]/C}]  -to [get_ports {fDAC2_out[11]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[12]/C}]  -to [get_ports {fDAC2_out[12]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[13]/C}]  -to [get_ports {fDAC2_out[13]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[14]/C}]  -to [get_ports {fDAC2_out[14]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[15]/C}]  -to [get_ports {fDAC2_out[15]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[1]/C}]  -to [get_ports {fDAC2_out[1]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[2]/C}]  -to [get_ports {fDAC2_out[2]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[3]/C}]  -to [get_ports {fDAC2_out[3]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[4]/C}]  -to [get_ports {fDAC2_out[4]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[5]/C}]  -to [get_ports {fDAC2_out[5]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[6]/C}]  -to [get_ports {fDAC2_out[6]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[7]/C}]  -to [get_ports {fDAC2_out[7]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[8]/C}]  -to [get_ports {fDAC2_out[8]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/s_out_reg[9]/C}]  -to [get_ports {fDAC2_out[9]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_2/sel_reg/C}]  -to [get_ports {fDAC2_sel}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[0]/C}]  -to [get_ports {fDAC3_out[0]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[10]/C}]  -to [get_ports {fDAC3_out[10]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[11]/C}]  -to [get_ports {fDAC3_out[11]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[12]/C}]  -to [get_ports {fDAC3_out[12]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[13]/C}]  -to [get_ports {fDAC3_out[13]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[14]/C}]  -to [get_ports {fDAC3_out[14]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[15]/C}]  -to [get_ports {fDAC3_out[15]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[1]/C}]  -to [get_ports {fDAC3_out[1]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[2]/C}]  -to [get_ports {fDAC3_out[2]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[3]/C}]  -to [get_ports {fDAC3_out[3]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[4]/C}]  -to [get_ports {fDAC3_out[4]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[5]/C}]  -to [get_ports {fDAC3_out[5]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[6]/C}]  -to [get_ports {fDAC3_out[6]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[7]/C}]  -to [get_ports {fDAC3_out[7]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[8]/C}]  -to [get_ports {fDAC3_out[8]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/s_out_reg[9]/C}]  -to [get_ports {fDAC3_out[9]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_3/sel_reg/C}]  -to [get_ports {fDAC3_sel}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[0]/C}]  -to [get_ports {fDAC4_out[0]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[10]/C}]  -to [get_ports {fDAC4_out[10]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[11]/C}]  -to [get_ports {fDAC4_out[11]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[12]/C}]  -to [get_ports {fDAC4_out[12]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[13]/C}]  -to [get_ports {fDAC4_out[13]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[14]/C}]  -to [get_ports {fDAC4_out[14]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[15]/C}]  -to [get_ports {fDAC4_out[15]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[1]/C}]  -to [get_ports {fDAC4_out[1]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[2]/C}]  -to [get_ports {fDAC4_out[2]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[3]/C}]  -to [get_ports {fDAC4_out[3]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[4]/C}]  -to [get_ports {fDAC4_out[4]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[5]/C}]  -to [get_ports {fDAC4_out[5]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[6]/C}]  -to [get_ports {fDAC4_out[6]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[7]/C}]  -to [get_ports {fDAC4_out[7]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[8]/C}]  -to [get_ports {fDAC4_out[8]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/s_out_reg[9]/C}]  -to [get_ports {fDAC4_out[9]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_4/sel_reg/C}]  -to [get_ports {fDAC4_sel}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[0]/C}]  -to [get_ports {fDAC5_out[0]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[10]/C}]  -to [get_ports {fDAC5_out[10]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[11]/C}]  -to [get_ports {fDAC5_out[11]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[12]/C}]  -to [get_ports {fDAC5_out[12]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[13]/C}]  -to [get_ports {fDAC5_out[13]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[14]/C}]  -to [get_ports {fDAC5_out[14]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[15]/C}]  -to [get_ports {fDAC5_out[15]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[1]/C}]  -to [get_ports {fDAC5_out[1]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[2]/C}]  -to [get_ports {fDAC5_out[2]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[3]/C}]  -to [get_ports {fDAC5_out[3]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[4]/C}]  -to [get_ports {fDAC5_out[4]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[5]/C}]  -to [get_ports {fDAC5_out[5]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[6]/C}]  -to [get_ports {fDAC5_out[6]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[7]/C}]  -to [get_ports {fDAC5_out[7]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[8]/C}]  -to [get_ports {fDAC5_out[8]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/s_out_reg[9]/C}]  -to [get_ports {fDAC5_out[9]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_5/sel_reg/C}]  -to [get_ports {fDAC5_sel}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[0]/C}]  -to [get_ports {fDAC6_out[0]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[10]/C}]  -to [get_ports {fDAC6_out[10]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[11]/C}]  -to [get_ports {fDAC6_out[11]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[12]/C}]  -to [get_ports {fDAC6_out[12]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[13]/C}]  -to [get_ports {fDAC6_out[13]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[14]/C}]  -to [get_ports {fDAC6_out[14]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[15]/C}]  -to [get_ports {fDAC6_out[15]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[1]/C}]  -to [get_ports {fDAC6_out[1]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[2]/C}]  -to [get_ports {fDAC6_out[2]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[3]/C}]  -to [get_ports {fDAC6_out[3]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[4]/C}]  -to [get_ports {fDAC6_out[4]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[5]/C}]  -to [get_ports {fDAC6_out[5]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[6]/C}]  -to [get_ports {fDAC6_out[6]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[7]/C}]  -to [get_ports {fDAC6_out[7]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[8]/C}]  -to [get_ports {fDAC6_out[8]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/s_out_reg[9]/C}]  -to [get_ports {fDAC6_out[9]}] -datapath_only 2.5
set_max_delay -from [get_pins {FAST_DAC_6/sel_reg/C}]  -to [get_ports {fDAC6_sel}] -datapath_only 2.5
set_max_delay -from [get_pins {ODDR_fDACclkB/C}]  -to [get_ports {fDACclkB_out}] -datapath_only 2.5
set_max_delay -from [get_pins {ODDR_fDACclkC/C}]  -to [get_ports {fDACclkC_out}] -datapath_only 2.5
