
####################################################################################
# Generated by Vivado 2020.1 built on 'Wed May 27 19:54:49 MDT 2020' by 'xbuild'
# Command Used: write_xdc -force -cell sDACinst ./Sources/xdc/sDACinst_phys.xdc
####################################################################################


####################################################################################
# Constraints from file : 'top_flpn.xdc'
####################################################################################

create_pblock pblock_sDACinst
add_cells_to_pblock [get_pblocks pblock_sDACinst] -top
resize_pblock [get_pblocks pblock_sDACinst] -add {SLICE_X0Y157:SLICE_X7Y199}
resize_pblock [get_pblocks pblock_sDACinst] -add {RAMB18_X0Y64:RAMB18_X0Y79}
resize_pblock [get_pblocks pblock_sDACinst] -add {RAMB36_X0Y32:RAMB36_X0Y39}
set_property CONTAIN_ROUTING 1 [get_pblocks pblock_sDACinst]
set_property IS_SOFT FALSE [get_pblocks pblock_sDACinst]
set_property PACKAGE_PIN G9 [get_ports sDAC_SDO_in]
set_property PACKAGE_PIN E11 [get_ports sDAC_SCK_out]
set_property PACKAGE_PIN G10 [get_ports sDAC_SDI_out]
set_property PACKAGE_PIN D11 [get_ports sDAC0_CS_out]
set_property PACKAGE_PIN H11 [get_ports sDAC1_CS_out]
set_property IOSTANDARD LVCMOS33 [get_ports sDAC_SDO_in]
set_property IOSTANDARD LVCMOS33 [get_ports sDAC_SCK_out]
set_property IOSTANDARD LVCMOS33 [get_ports sDAC_SDI_out]
set_property IOSTANDARD LVCMOS33 [get_ports sDAC0_CS_out]
set_property IOSTANDARD LVCMOS33 [get_ports sDAC1_CS_out]

# User Generated miscellaneous constraints 

set_property HD.PARTITION true [current_design]
