create_clock -period 10 -name sADC_clk_int.clk [get_ports {clk}] -waveform { 0.000000 5.000000  }
set_property HD.CLK_SRC BUFGCTRL_X0Y8 [get_ports {clk}] 
create_clock -period 10 -name sADC_clk_in_int.data_in_clk [get_ports {data_in_clk}] -waveform { 0.000000 5.000000  }
set_property HD.CLK_SRC BUFGCTRL_X0Y9 [get_ports {data_in_clk}] 
set_max_delay -from [get_pins {ODDR_sADC_SCKI/C}]  -to [get_ports {sADC_SCKI_out}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/CNV_reg_lopt_replica/C}]  -to [get_ports {sADC_CNV_out}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/LTC2335_16_SPI_inst/CS0_reg/C}]  -to [get_ports {sADC_CS0_out}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/LTC2335_16_SPI_inst/CS0_reg/C}]  -to [get_ports {sADC_CS1_out}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/LTC2335_16_SPI_inst/SDO_reg/C}]  -to [get_ports {sADC_SDI_out}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][0]/C}]  -to [get_ports {s_in_0[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][10]/C}]  -to [get_ports {s_in_0[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][11]/C}]  -to [get_ports {s_in_0[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][12]/C}]  -to [get_ports {s_in_0[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][13]/C}]  -to [get_ports {s_in_0[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][14]/C}]  -to [get_ports {s_in_0[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][15]/C}]  -to [get_ports {s_in_0[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][1]/C}]  -to [get_ports {s_in_0[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][2]/C}]  -to [get_ports {s_in_0[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][3]/C}]  -to [get_ports {s_in_0[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][4]/C}]  -to [get_ports {s_in_0[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][5]/C}]  -to [get_ports {s_in_0[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][6]/C}]  -to [get_ports {s_in_0[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][7]/C}]  -to [get_ports {s_in_0[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][8]/C}]  -to [get_ports {s_in_0[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[0][9]/C}]  -to [get_ports {s_in_0[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][0]/C}]  -to [get_ports {s_in_1[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][10]/C}]  -to [get_ports {s_in_1[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][11]/C}]  -to [get_ports {s_in_1[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][12]/C}]  -to [get_ports {s_in_1[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][13]/C}]  -to [get_ports {s_in_1[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][14]/C}]  -to [get_ports {s_in_1[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][15]/C}]  -to [get_ports {s_in_1[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][1]/C}]  -to [get_ports {s_in_1[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][2]/C}]  -to [get_ports {s_in_1[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][3]/C}]  -to [get_ports {s_in_1[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][4]/C}]  -to [get_ports {s_in_1[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][5]/C}]  -to [get_ports {s_in_1[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][6]/C}]  -to [get_ports {s_in_1[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][7]/C}]  -to [get_ports {s_in_1[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][8]/C}]  -to [get_ports {s_in_1[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[1][9]/C}]  -to [get_ports {s_in_1[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][0]/C}]  -to [get_ports {s_in_2[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][10]/C}]  -to [get_ports {s_in_2[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][11]/C}]  -to [get_ports {s_in_2[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][12]/C}]  -to [get_ports {s_in_2[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][13]/C}]  -to [get_ports {s_in_2[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][14]/C}]  -to [get_ports {s_in_2[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][15]/C}]  -to [get_ports {s_in_2[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][1]/C}]  -to [get_ports {s_in_2[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][2]/C}]  -to [get_ports {s_in_2[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][3]/C}]  -to [get_ports {s_in_2[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][4]/C}]  -to [get_ports {s_in_2[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][5]/C}]  -to [get_ports {s_in_2[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][6]/C}]  -to [get_ports {s_in_2[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][7]/C}]  -to [get_ports {s_in_2[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][8]/C}]  -to [get_ports {s_in_2[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[2][9]/C}]  -to [get_ports {s_in_2[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][0]/C}]  -to [get_ports {s_in_3[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][10]/C}]  -to [get_ports {s_in_3[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][11]/C}]  -to [get_ports {s_in_3[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][12]/C}]  -to [get_ports {s_in_3[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][13]/C}]  -to [get_ports {s_in_3[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][14]/C}]  -to [get_ports {s_in_3[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][15]/C}]  -to [get_ports {s_in_3[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][1]/C}]  -to [get_ports {s_in_3[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][2]/C}]  -to [get_ports {s_in_3[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][3]/C}]  -to [get_ports {s_in_3[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][4]/C}]  -to [get_ports {s_in_3[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][5]/C}]  -to [get_ports {s_in_3[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][6]/C}]  -to [get_ports {s_in_3[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][7]/C}]  -to [get_ports {s_in_3[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][8]/C}]  -to [get_ports {s_in_3[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[3][9]/C}]  -to [get_ports {s_in_3[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][0]/C}]  -to [get_ports {s_in_4[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][10]/C}]  -to [get_ports {s_in_4[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][11]/C}]  -to [get_ports {s_in_4[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][12]/C}]  -to [get_ports {s_in_4[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][13]/C}]  -to [get_ports {s_in_4[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][14]/C}]  -to [get_ports {s_in_4[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][15]/C}]  -to [get_ports {s_in_4[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][1]/C}]  -to [get_ports {s_in_4[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][2]/C}]  -to [get_ports {s_in_4[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][3]/C}]  -to [get_ports {s_in_4[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][4]/C}]  -to [get_ports {s_in_4[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][5]/C}]  -to [get_ports {s_in_4[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][6]/C}]  -to [get_ports {s_in_4[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][7]/C}]  -to [get_ports {s_in_4[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][8]/C}]  -to [get_ports {s_in_4[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[4][9]/C}]  -to [get_ports {s_in_4[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][0]/C}]  -to [get_ports {s_in_5[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][10]/C}]  -to [get_ports {s_in_5[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][11]/C}]  -to [get_ports {s_in_5[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][12]/C}]  -to [get_ports {s_in_5[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][13]/C}]  -to [get_ports {s_in_5[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][14]/C}]  -to [get_ports {s_in_5[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][15]/C}]  -to [get_ports {s_in_5[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][1]/C}]  -to [get_ports {s_in_5[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][2]/C}]  -to [get_ports {s_in_5[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][3]/C}]  -to [get_ports {s_in_5[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][4]/C}]  -to [get_ports {s_in_5[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][5]/C}]  -to [get_ports {s_in_5[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][6]/C}]  -to [get_ports {s_in_5[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][7]/C}]  -to [get_ports {s_in_5[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][8]/C}]  -to [get_ports {s_in_5[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[5][9]/C}]  -to [get_ports {s_in_5[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][0]/C}]  -to [get_ports {s_in_6[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][10]/C}]  -to [get_ports {s_in_6[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][11]/C}]  -to [get_ports {s_in_6[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][12]/C}]  -to [get_ports {s_in_6[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][13]/C}]  -to [get_ports {s_in_6[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][14]/C}]  -to [get_ports {s_in_6[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][15]/C}]  -to [get_ports {s_in_6[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][1]/C}]  -to [get_ports {s_in_6[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][2]/C}]  -to [get_ports {s_in_6[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][3]/C}]  -to [get_ports {s_in_6[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][4]/C}]  -to [get_ports {s_in_6[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][5]/C}]  -to [get_ports {s_in_6[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][6]/C}]  -to [get_ports {s_in_6[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][7]/C}]  -to [get_ports {s_in_6[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][8]/C}]  -to [get_ports {s_in_6[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[6][9]/C}]  -to [get_ports {s_in_6[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][0]/C}]  -to [get_ports {s_in_7[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][10]/C}]  -to [get_ports {s_in_7[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][11]/C}]  -to [get_ports {s_in_7[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][12]/C}]  -to [get_ports {s_in_7[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][13]/C}]  -to [get_ports {s_in_7[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][14]/C}]  -to [get_ports {s_in_7[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][15]/C}]  -to [get_ports {s_in_7[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][1]/C}]  -to [get_ports {s_in_7[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][2]/C}]  -to [get_ports {s_in_7[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][3]/C}]  -to [get_ports {s_in_7[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][4]/C}]  -to [get_ports {s_in_7[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][5]/C}]  -to [get_ports {s_in_7[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][6]/C}]  -to [get_ports {s_in_7[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][7]/C}]  -to [get_ports {s_in_7[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][8]/C}]  -to [get_ports {s_in_7[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data0_reg[7][9]/C}]  -to [get_ports {s_in_7[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][0]/C}]  -to [get_ports {s_in_8[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][10]/C}]  -to [get_ports {s_in_8[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][11]/C}]  -to [get_ports {s_in_8[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][12]/C}]  -to [get_ports {s_in_8[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][13]/C}]  -to [get_ports {s_in_8[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][14]/C}]  -to [get_ports {s_in_8[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][15]/C}]  -to [get_ports {s_in_8[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][1]/C}]  -to [get_ports {s_in_8[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][2]/C}]  -to [get_ports {s_in_8[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][3]/C}]  -to [get_ports {s_in_8[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][4]/C}]  -to [get_ports {s_in_8[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][5]/C}]  -to [get_ports {s_in_8[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][6]/C}]  -to [get_ports {s_in_8[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][7]/C}]  -to [get_ports {s_in_8[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][8]/C}]  -to [get_ports {s_in_8[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[0][9]/C}]  -to [get_ports {s_in_8[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][0]/C}]  -to [get_ports {s_in_9[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][10]/C}]  -to [get_ports {s_in_9[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][11]/C}]  -to [get_ports {s_in_9[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][12]/C}]  -to [get_ports {s_in_9[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][13]/C}]  -to [get_ports {s_in_9[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][14]/C}]  -to [get_ports {s_in_9[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][15]/C}]  -to [get_ports {s_in_9[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][1]/C}]  -to [get_ports {s_in_9[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][2]/C}]  -to [get_ports {s_in_9[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][3]/C}]  -to [get_ports {s_in_9[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][4]/C}]  -to [get_ports {s_in_9[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][5]/C}]  -to [get_ports {s_in_9[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][6]/C}]  -to [get_ports {s_in_9[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][7]/C}]  -to [get_ports {s_in_9[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][8]/C}]  -to [get_ports {s_in_9[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[1][9]/C}]  -to [get_ports {s_in_9[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][0]/C}]  -to [get_ports {s_in_10[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][10]/C}]  -to [get_ports {s_in_10[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][11]/C}]  -to [get_ports {s_in_10[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][12]/C}]  -to [get_ports {s_in_10[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][13]/C}]  -to [get_ports {s_in_10[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][14]/C}]  -to [get_ports {s_in_10[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][15]/C}]  -to [get_ports {s_in_10[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][1]/C}]  -to [get_ports {s_in_10[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][2]/C}]  -to [get_ports {s_in_10[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][3]/C}]  -to [get_ports {s_in_10[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][4]/C}]  -to [get_ports {s_in_10[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][5]/C}]  -to [get_ports {s_in_10[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][6]/C}]  -to [get_ports {s_in_10[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][7]/C}]  -to [get_ports {s_in_10[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][8]/C}]  -to [get_ports {s_in_10[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[2][9]/C}]  -to [get_ports {s_in_10[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][0]/C}]  -to [get_ports {s_in_11[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][10]/C}]  -to [get_ports {s_in_11[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][11]/C}]  -to [get_ports {s_in_11[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][12]/C}]  -to [get_ports {s_in_11[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][13]/C}]  -to [get_ports {s_in_11[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][14]/C}]  -to [get_ports {s_in_11[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][15]/C}]  -to [get_ports {s_in_11[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][1]/C}]  -to [get_ports {s_in_11[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][2]/C}]  -to [get_ports {s_in_11[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][3]/C}]  -to [get_ports {s_in_11[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][4]/C}]  -to [get_ports {s_in_11[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][5]/C}]  -to [get_ports {s_in_11[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][6]/C}]  -to [get_ports {s_in_11[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][7]/C}]  -to [get_ports {s_in_11[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][8]/C}]  -to [get_ports {s_in_11[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[3][9]/C}]  -to [get_ports {s_in_11[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][0]/C}]  -to [get_ports {s_in_12[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][10]/C}]  -to [get_ports {s_in_12[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][11]/C}]  -to [get_ports {s_in_12[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][12]/C}]  -to [get_ports {s_in_12[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][13]/C}]  -to [get_ports {s_in_12[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][14]/C}]  -to [get_ports {s_in_12[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][15]/C}]  -to [get_ports {s_in_12[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][1]/C}]  -to [get_ports {s_in_12[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][2]/C}]  -to [get_ports {s_in_12[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][3]/C}]  -to [get_ports {s_in_12[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][4]/C}]  -to [get_ports {s_in_12[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][5]/C}]  -to [get_ports {s_in_12[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][6]/C}]  -to [get_ports {s_in_12[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][7]/C}]  -to [get_ports {s_in_12[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][8]/C}]  -to [get_ports {s_in_12[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[4][9]/C}]  -to [get_ports {s_in_12[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][0]/C}]  -to [get_ports {s_in_13[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][10]/C}]  -to [get_ports {s_in_13[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][11]/C}]  -to [get_ports {s_in_13[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][12]/C}]  -to [get_ports {s_in_13[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][13]/C}]  -to [get_ports {s_in_13[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][14]/C}]  -to [get_ports {s_in_13[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][15]/C}]  -to [get_ports {s_in_13[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][1]/C}]  -to [get_ports {s_in_13[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][2]/C}]  -to [get_ports {s_in_13[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][3]/C}]  -to [get_ports {s_in_13[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][4]/C}]  -to [get_ports {s_in_13[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][5]/C}]  -to [get_ports {s_in_13[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][6]/C}]  -to [get_ports {s_in_13[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][7]/C}]  -to [get_ports {s_in_13[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][8]/C}]  -to [get_ports {s_in_13[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[5][9]/C}]  -to [get_ports {s_in_13[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][0]/C}]  -to [get_ports {s_in_14[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][10]/C}]  -to [get_ports {s_in_14[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][11]/C}]  -to [get_ports {s_in_14[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][12]/C}]  -to [get_ports {s_in_14[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][13]/C}]  -to [get_ports {s_in_14[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][14]/C}]  -to [get_ports {s_in_14[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][15]/C}]  -to [get_ports {s_in_14[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][1]/C}]  -to [get_ports {s_in_14[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][2]/C}]  -to [get_ports {s_in_14[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][3]/C}]  -to [get_ports {s_in_14[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][4]/C}]  -to [get_ports {s_in_14[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][5]/C}]  -to [get_ports {s_in_14[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][6]/C}]  -to [get_ports {s_in_14[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][7]/C}]  -to [get_ports {s_in_14[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][8]/C}]  -to [get_ports {s_in_14[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[6][9]/C}]  -to [get_ports {s_in_14[9]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][0]/C}]  -to [get_ports {s_in_15[0]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][10]/C}]  -to [get_ports {s_in_15[10]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][11]/C}]  -to [get_ports {s_in_15[11]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][12]/C}]  -to [get_ports {s_in_15[12]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][13]/C}]  -to [get_ports {s_in_15[13]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][14]/C}]  -to [get_ports {s_in_15[14]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][15]/C}]  -to [get_ports {s_in_15[15]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][1]/C}]  -to [get_ports {s_in_15[1]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][2]/C}]  -to [get_ports {s_in_15[2]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][3]/C}]  -to [get_ports {s_in_15[3]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][4]/C}]  -to [get_ports {s_in_15[4]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][5]/C}]  -to [get_ports {s_in_15[5]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][6]/C}]  -to [get_ports {s_in_15[6]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][7]/C}]  -to [get_ports {s_in_15[7]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][8]/C}]  -to [get_ports {s_in_15[8]}] -datapath_only 5
set_max_delay -from [get_pins {slow_ADC_inst/data1_reg[7][9]/C}]  -to [get_ports {s_in_15[9]}] -datapath_only 5
