
####################################################################################
# Generated by Vivado 2020.1 built on 'Wed May 27 19:54:49 MDT 2020' by 'xbuild'
# Command Used: write_xdc -force -cell SR_CTRL0 ./Sources/xdc/SR_CTRL0_phys.xdc
####################################################################################


####################################################################################
# Constraints from file : 'top_flpn.xdc'
####################################################################################

create_pblock pblock_SR_CTRL0
add_cells_to_pblock [get_pblocks pblock_SR_CTRL0] -top
resize_pblock [get_pblocks pblock_SR_CTRL0] -add {SLICE_X8Y0:SLICE_X11Y25}
set_property CONTAIN_ROUTING 1 [get_pblocks pblock_SR_CTRL0]
set_property IS_SOFT FALSE [get_pblocks pblock_SR_CTRL0]
set_property PACKAGE_PIN E21 [get_ports STROBE_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports STROBE_OUT]
set_property PACKAGE_PIN D24 [get_ports CLK_SR]
set_property IOSTANDARD LVCMOS25 [get_ports CLK_SR]
set_property PACKAGE_PIN E22 [get_ports SR_IN_INT]
set_property IOSTANDARD LVCMOS25 [get_ports SR_IN_INT]
set_property PACKAGE_PIN D23 [get_ports SR_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports SR_OUT]

# User Generated miscellaneous constraints 

set_property HD.PARTITION true [current_design]
